### ISSUE TITLE
Buzzer when battery is about to run out

### ISSUE THREAD

**Issue by mmroden** [tetrabiodistributed/PAPRA-PCB#14]
Feature request: when the battery is low, an audible signal as well as the gauge would be helpful

**Comment by mmroden** [comment]
version 0.4 at the earliest

**Comment by mechatroniks-git** [comment]
Will add this buzzer to v0.5
12V Buzzer - https://lcsc.com/product-detail/Buzzers_Fengming-YS-MBZ12095DYB12_C409840.html/?href=jlc-SMT
[datasheet](https://datasheet.lcsc.com/szlcsc/1912171631_Fengming-YS-MBZ12095DYB12_C409840.pdf)

**Comment by mechatroniks-git** [comment]
Buzzer sourced locally: https://www.jameco.com/z/CEM-1212C-CUI-Electromagnetic-Audio-Buzzer-12V-35mA-85dB-2-3kHz_2286415.html
 https://www.jameco.com/Jameco/Products/ProdDS/2286415.pdf

**Comment by mmroden** [comment]
closed by #49

**Comment by mechatroniks-git** [comment]
Digikey Buzzer: https://www.digikey.com/en/products/detail/intervox/BRT1209P-12-C/13693933
