### ISSUE TITLE
Papra fan box PCB engineering drawing

### ISSUE THREAD

**Issue by darraghbr** [tetrabiodistributed/PAPRA-PCB#17]
Submit an engineering diagram for the Papra fan box PCB in PDF

**Comment by darraghbr** [comment]
First draft for review by @mechatroniks-git 

[D-TET-001101-0 PapraFanBoxPCBA Drawing.pdf](https://github.com/tetrabiodistributed/PAPRA-PCB/files/5971070/D-TET-001101-0.PapraFanBoxPCBA.Drawing.pdf)

**Comment by mmroden** [comment]
Version 0, not with the new airtight connectors

**Comment by mechatroniks-git** [comment]
This version looks good. 

The sealed connector PCB, v0.3 has been committed, ready for review

**Comment by darraghbr** [comment]
Updated for new DC jack and general tidy up.

[D-TET-001101-0 Papra Fan Box PCBA Drawing.pdf](https://github.com/tetrabiodistributed/PAPRA-PCB/files/6016248/D-TET-001101-0.Papra.Fan.Box.PCBA.Drawing.pdf)

**Comment by mechatroniks-git** [comment]
Looks good, but maybe something moved in assembly? 
![image](https://user-images.githubusercontent.com/57600622/108609216-72448280-7381-11eb-9c03-e5374181ad26.png)

**Comment by darraghbr** [comment]
The previous version of the drawing also showed a gap between the components and the board? If you want me to fix it I will.

**Comment by mmroden** [comment]
Closed per discussion, work has been completed as there is a drawing for the papra pcba
