### ISSUE TITLE
Move PAPRa firmware to designated repo

### ISSUE THREAD

**Issue by capsulecorplab** [tetrabiodistributed/PAPRA-PCB#19]
Personally, I would move the PAPRa firmware to a designated repo, as to provide clearer association of the codebase to its license and separation of version history between PCB & firmware code. The firmware repo can then be added as a submodule, if the PCB repo must reference the firmware - keeping in mind that submodules need to be updated.

**Comment by mechatroniks-git** [comment]
@capsulecorplab Do I need to do this in a manner that preserves history, or just create a new Repo and copy the files over and remove them from here?

**Comment by capsulecorplab** [comment]
@mechatroniks-git I would probably do the latter, then add replace the firmware folder in this repo with a submodule that points to the firmware repo. https://github.blog/2016-02-01-working-with-submodules/

**Comment by mechatroniks-git** [comment]
https://github.com/tetrabiodistributed/papra-pcb-firmware created.

**Comment by mmroden** [comment]
closed by #49
