### ISSUE TITLE
Close the gap uncovered in the engineering drawing submitted for #17

### ISSUE THREAD

**Issue by mmroden** [tetrabiodistributed/PAPRA-PCB#22]
There is a gap on the fan box PCB that needs to be closed

**Comment by mmroden** [comment]
This was found in issue #17

**Comment by mechatroniks-git** [comment]
Parts aligned and updated rigid group in Fusion.
![image](https://user-images.githubusercontent.com/57600622/108745911-85299500-74f0-11eb-8e56-d03608f13646.png)
