### ISSUE TITLE
BOM scrub

### ISSUE THREAD

**Issue by mmroden** [tetrabiodistributed/PAPRA-PCB#29]
Need to check to make sure that the BOM is updated, and order necessary parts.

Order fans through digikey

**Comment by mechatroniks-git** [comment]
I built a DigiKey Cart for the PAPR components I need. See https://www.digikey.com/short/r80dwtpq

@DHHwangPhD Can you add in the blowers you wish to test?

**Comment by mmroden** [comment]
requires amazon blower as well as the digikey fan so that we can compare

**Comment by mechatroniks-git** [comment]
I added a couple of blower candidates to the cart using a dart board and blind fold selection process.
![image](https://user-images.githubusercontent.com/57600622/110196983-1fe17800-7dfd-11eb-8b65-bb70a4deb655.png)

**Comment by mechatroniks-git** [comment]
New cart: https://www.digikey.com/short/2jnh3hmq

**Comment by darraghbr** [comment]
That NMB SKU is a PWM 3 wire fan, I assume you don't want that?

**Comment by mechatroniks-git** [comment]
Final Cart https://www.digikey.com/short/wd4tffcn

**Comment by mechatroniks-git** [comment]
And will need 1 of these for crimping: https://www.amazon.com/IWISS-Terminal-Crimping-SN-01BM-0-08-0-5mm/dp/B019ARWWFY
