### ISSUE TITLE
waterproof/splashproof the papra?  How to do that?

### ISSUE THREAD

**Issue by mmroden** [tetrabiodistributed/PAPRA-PCB#34]

**Comment by darraghbr** [comment]
We could use a set of louvres on the fan box to hopefully keep the worst of any rain etc off the filter pack. 

It may limit which orientation you can mount the fan box.

**Comment by darraghbr** [comment]
For the M12 controlled we could use a 3D printed TPU or other flexible gasket that seals between the battery and the M12 housing. The lid could then be attached permanently with a waterproof adhesive and IP rated potentiometers and DC jacks utilised.

**Comment by darraghbr** [comment]
An example of the louvers is something like what are used on armoured fighting vehicles to protect the radiators and air intakes. 

They are also used on dirt bikes to protect the radiator from debris. 

![image](https://user-images.githubusercontent.com/31858409/110976830-4f423880-8359-11eb-8e78-c7970282517d.png)

**Comment by mmroden** [comment]
Handled by #37 and #38 in this project

**Comment by mmroden** [comment]
redundant to #55 and work done in the papr-print-files
