### ISSUE TITLE
Bad fan boards can cook the m12 controller boards

### ISSUE THREAD

**Issue by mechatroniks-git** [tetrabiodistributed/PAPRA-PCB#36]
When testing a "bad" fan board, multiple m12 v2 controller boards and a Milwaukee m12 charger were all rendered nonfunctional once power was applied to the system when testing a fan.

**Comment by mmroden** [comment]
Should be solved by the 0.3 board

**Comment by mmroden** [comment]
Now will be solved by not having a fan board

**Comment by mechatroniks-git** [comment]
Possible bad wiring in fan box (dead short on fan power wiring or in fan itself) can cause same issue. PCB V3+ should protect.

**Comment by mechatroniks-git** [comment]
Added 1A fuse on 12V to DC blower, tested with dead short on fan output, board survived and is fully functional once short is removed.  Recommend adding 2nd fuse to DC blower on v.5 PCB, so board should have 2 fuses in parallel, one for DC blower, one for everything else.

![image](https://user-images.githubusercontent.com/57600622/115125293-f1b69280-9f7b-11eb-9414-7711a947cacd.png)

**Comment by mechatroniks-git** [comment]
![image](https://user-images.githubusercontent.com/57600622/115125393-a05ad300-9f7c-11eb-808e-a92ea1bc9a5f.png)

![image](https://user-images.githubusercontent.com/57600622/115125419-c2ecec00-9f7c-11eb-94bc-723b404f9a73.png)

**Comment by mmroden** [comment]
Closed by #43

**Comment by mmroden** [comment]
closed by #49
