### ISSUE TITLE
Update M12 board with BNC connector

### ISSUE THREAD

**Issue by mmroden** [tetrabiodistributed/PAPRA-PCB#37]

**Comment by mechatroniks-git** [comment]
This is a decent, low cost BNC. If nobody objects, I'll design it in.
https://octopart.com/5227161-9-te+connectivity-39536535?r=sp
https://www.te.com/usa-en/product-5227161-9.html?te_bu=Cor&te_type=srch&te_campaign=oct_usa_cor-oct-usa-srch-selectmktg-fy21-octopart-feed_sma-1735_8&elqCampaignId=95671
