### ISSUE TITLE
Investigate 0.2 papra board failure

### ISSUE THREAD

**Issue by mmroden** [tetrabiodistributed/PAPRA-PCB#40]
Something failed in Patrick's PAPR, need to understand why

**Comment by mechatroniks-git** [comment]
ATtiny failed

![image](https://user-images.githubusercontent.com/57600622/113485181-3bbe5500-9461-11eb-9459-fb03d1f54ab4.png)

**Comment by mechatroniks-git** [comment]
Replacing ATtiny solved issue, not sure what caused it

**Comment by mechatroniks-git** [comment]
Replaced with ATtiny1624 (2-Series) chip and programmed with Megatinycore v2.3.1 using this code: https://github.com/tetrabiodistributed/PAPRA-PCB/blob/c38be3ee90f81fe9fc7fcec78938d70674fdf67d/firmware/papracode/papracode.ino. Board is fully functional, will keep testing.

**Comment by mechatroniks-git** [comment]
Failure likely caused by GND-SENSE input to microcontroller

**Comment by mmroden** [comment]
fixed by version 0.4, #43
