### ISSUE TITLE
Investigate blown rev .2 PCB

### ISSUE THREAD

**Issue by mechatroniks-git** [tetrabiodistributed/PAPRA-PCB#41]
At the end of the 4/10/22 build party, tested new IP rated DC cable, which had short, fried Mark's M12 control board.

**Comment by mechatroniks-git** [comment]
Powered up m12 board, found 5V regulator was hot and only outputting 1.4 VDC.

**Comment by mechatroniks-git** [comment]
MOSFET also blown. Replaced, board is now working. Same failure mode, shorted output can fry the MOSFET and ATTINY. Will be resolved in V.5 of PCB, for now, don't short the output and you will be good.

ATtiny was replaced with 214, but 2K code space fills up, so had to remove startup knight-rider LED sequence to fit. Same issue likely with the 204 flavor. Also, v2.3.1 of the MegaTinyCore has a bug with this chip, created issue. V2.9 works.

**Comment by darraghbr** [comment]
It might be worth adding an eFuse IC? It would replace the polyfuse, and could provide overcurrent, overvoltage and short protection.

https://www.ti.com/power-management/power-switches/efuse-hotswap-controllers/overview.html?keyMatch=EFUSE&tisearch=search-everything

**Comment by mmroden** [comment]
closed by #43
