### ISSUE TITLE
test that protection circuitry actually protects

### ISSUE THREAD

**Issue by mmroden** [tetrabiodistributed/PAPRA-PCB#47]
Going to also need to put that in the testing docs

**Comment by mechatroniks-git** [comment]
Tested on .4 board by shorting the output to the fan, board survived several attempts

**Comment by mechatroniks-git** [comment]
Tested v.5 PCB
1. Shorted BNC while adjusting the fan output
2. Applied reverse polarity to the battery terminals

In both cases, board suffered no damage and remained fully functional.

**Comment by mmroden** [comment]
closed by #49
