### ISSUE TITLE
Test megaTinyCore v2.3.2 

### ISSUE THREAD

**Issue by darraghbr** [tetrabiodistributed/PAPRA-PCB#48]
Looks like there is a new version of megaTinyCore, hopefully it resolves some of the timer issues @mechatroniks-git had with the now deprecated 2.3.1.

**Comment by mechatroniks-git** [comment]
Yes, looks fixed. I compiled with 2.3.2 for 204, 814, 1614 and 1624, no more compile errors.

**Comment by mmroden** [comment]
dependent on the buzzers arriving

**Comment by mechatroniks-git** [comment]
2.3.2 works, compiled and downloaded to 1624 target.

**Comment by mmroden** [comment]
tested by and works with 0.5 (#49)
