### ISSUE TITLE
Battery Level Indicator Check

### ISSUE THREAD

**Issue by DHHwangPhD** [tetrabiodistributed/PAPRA-PCB#5]
With 3500 mA/hr battery,
Last light to flashing light = 1h 15mins
Flashing light to shut down = 13 mins

**Comment by mechatroniks-git** [comment]
Battery LEDs are close, but don't exactly align with the Milwaukee M12 LEDs (these are 4 LEDs on the DC charger that readout battery life). A compete measurement needs to happen over 4+ hours while constantly checking the battery readout on the M12 charger by pressing a button on the charger. Simultaneously, need to read serial stream from the board to get battery ADC readings at the moment the M12 LED readout changes.

**Comment by mmroden** [comment]
This is a nice to have, not critical

**Comment by mmroden** [comment]
This is done
