### ISSUE TITLE
How-to repair burnt out microcontroller

### ISSUE THREAD

**Issue by capsulecorplab** [tetrabiodistributed/PAPRA-PCB#57]
Write a how-to guide for repairing a burnt out microcontroller on the PAPRA-PCB

**Comment by capsulecorplab** [comment]
Any ATtinyXY4 should work, where X = 4/8/16 and Y=0/1/2. Best part to use is ATtiny1614-SSN

**Comment by capsulecorplab** [comment]
But for debugging, look at this: https://github.com/tetrabiodistributed/PAPRA-PCB/issues/41#issuecomment-821879576 and https://github.com/tetrabiodistributed/PAPRA-PCB/issues/40

**Comment by capsulecorplab** [comment]
need to cut the GND-SENSE line to prevent it from happening again

**Comment by capsulecorplab** [comment]
will need a UPDI programmer: https://github.com/SpenceKonde/AVR-Guidance/blob/master/UPDI/jtag2updi.md

**Comment by capsulecorplab** [comment]
most of these issues will only apply to the .2 rev

**Comment by mmroden** [comment]
OBE
