### ISSUE TITLE
Investigate a potentiometer with set positions rather than a continuous adjustment

### ISSUE THREAD

**Issue by mmroden** [tetrabiodistributed/PAPRA-PCB#58]
so we can be sure to hit 4 CFM on at least one setting

**Comment by mechatroniks-git** [comment]
How many positions?

We could have 2 - just on & off. 

We're currently using this part: [P091S-FC20BR](https://www.ttelectronics.com/products/categories/potentiometers/potentiometers/p082d/)

You can build a part number with 1, 11,21 or 41 detents and be a drop in replacement, but not seeing any part availability beyond a Non-Stocked Lead-Time 23 Weeks with a minimum order of 1820 pieces. 

There are other parts that are similar, but would require a new PCB and possibly changes to the housing

![image](https://user-images.githubusercontent.com/57600622/173237484-c85d10d6-7fa5-4f61-8b32-e94651e55953.png)
