### ISSUE TITLE
Investigate replacing the e-fuse with a toshiba part

### ISSUE THREAD

**Issue by mmroden** [tetrabiodistributed/PAPRA-PCB#67]
Efuses are hard to find, we need a replacement part.  This ticket is an investigation for whether this part can replace the existing efuse.

https://www.digikey.co.uk/en/products/detail/toshiba-semiconductor-and-storage/TCKE800NL-RF/12324957

**Comment by mechatroniks-git** [comment]
Quick comparison of features:

![image](https://user-images.githubusercontent.com/57600622/184669293-26a0f6e6-1822-470a-9220-78568b769c1a.png)

##TLDR:

### Toshiba
- Toshiba part will be easier to solder and should have less components required
- Toshiba requires external MOSFET for reverse polarity protection

### TI
- TI part is cheaper and more featured
- TI has adjustable Overvoltage, Toshiba has a fixed value @ 15.1V
- TI has slightly lower on-resistance (less heat) - but still good
- TI has status outputs
- TI has better nuisance tripping resilience
 
![image](https://user-images.githubusercontent.com/57600622/184671255-a71499c9-f15c-47a5-bde0-1e2ca803ab65.png)

**Comment by mechatroniks-git** [comment]
![image](https://user-images.githubusercontent.com/57600622/184672851-acc8d45a-2871-4392-bd3d-cdb5326c5eda.png)

https://octopart.com/tcke812na%2Crf-toshiba-109207110?r=sp
vs
https://octopart.com/tps259472arpwr-texas+instruments-113046828?r=sp

**Comment by mechatroniks-git** [comment]
TI circuit:

![image](https://user-images.githubusercontent.com/57600622/184674567-511a34ea-4369-4a7e-a65c-c9133aa864d6.png)

Toshiba Circuit:
![image](https://user-images.githubusercontent.com/57600622/184674333-05ff6a29-9669-48a7-8ec4-5740edd73451.png)

**Comment by darraghbr** [comment]
Just a couple of quick agenda items for the meeting.

- What is the stock like for the transient suppression diodes and the external FET
- Do we currently take advantage of the reverse polarity protection on the current board rev (I seem to recall that we do) and do we think that it is necessary to keep that functionality (I think it is)

**Comment by mechatroniks-git** [comment]
Reverse polarity is a good thing, certainly worth the $.31 per board.

These are the recommended parts, all made by Toshiba. Cost at 100 board qty.  Lots of stock at the moment. 
TVS: Lots of stock, $0.20/board [octopart](https://octopart.com/df2s23p2ctc%2Cl3f-toshiba-87695657?r=sp)
SBD: Lots of stock, $0.22/board [octopart](https://octopart.com/cuhs20s30%2Ch3f-toshiba-97210178?r=sp)
FET: Lots of stock, $0.31/board [octopart](https://octopart.com/ssm6k513nu%2Clf-toshiba-75194178?r=sp)

**Comment by darraghbr** [comment]
https://www.digikey.co.uk/en/products/detail/toshiba-semiconductor-and-storage/TCKE812NA-RF/12324959?s=N4IgTCBcDaICoGEDSBRAHARjAOQIIgF0BfIA

Updated digikey link for the correct over voltage and stock

**Comment by mechatroniks-git** [comment]
With Texas Instruments showing stock, request was made to order 250 parts for stock to avoid having to design in the Toshiba part. 

Closing this issue for the time being.
