### ISSUE TITLE
PWM output pin chosen has configuration limitations

### ISSUE THREAD

**Issue by mechatroniks-git** [tetrabiodistributed/PAPRA-PCB#8]
WO3 is currently used, ideally it should be WO0 - WO2 to avoid using TCA0 in split-mode.  See: https://github.com/SpenceKonde/megaTinyCore/blob/master/megaavr/extras/TakingOverTCA0.md

**Comment by darraghbr** [comment]
Is it worth testing this with a bodge wire to see if the proposed changes have the desired impact?
